version: '3.2'

services:

  nats-streaming:
    container_name: nats-streaming
    entrypoint: "/nats-streaming-server -DV"
    image: nats-streaming
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
